version: "3.4"

services:
  crm-fe:
    image: crm-fe
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      VITE_BE_BASE_URL: http://kienvt.tech/api/v1
    ports:
      - 80:5000
